export const enum ROUTES_ENUM {
  Dashboard = "dashboard",
  Info = "info",
  Profile = "profile",
  Admin = "admin",
  Login = "login",
  BlockList = "block-list",
  BlockDeckList = "block-deck-list",
  ManageBlock = "manage-block",
  BlockDetails = "block-details",
  BlockForm = "block-form",
  ManageBlockDeck = "manage-block-deck",
  BlockDeckDetails = "block-deck-details",
  BlockDeckForm = "block-deck-form",
}
